baseURL: "https://francescortu.github.io/"
publishDir: "docs"
title: Francesco Ortu
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Francesco Ortu
  description: "Francesco Ortu"
  keywords: [Blog, Portfolio, PaperMod, Francesco, Ortu, NLP, Deep Learning, AI, ML, machine learning]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  mainSections:
    - blog
    - portfolio

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Francesco Ortu"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Hi there, I'm Francesco 👋
    subtitle: "Early Stage Researcher (Borsista di Ricerca) at AREA Science Park \n\n NLP and Intepretability of LLM"
    imageUrl: "/images/profilo2.png"
    imageWidth: 250
    imageHeight: 250
    imageTitle: my image
    buttons:
      - name: About Me
        url: /bio/
    # add new buttons
    

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/francescortu"
    - name: twitter
      url: "https://twitter.com/francescortu"
    - name: linkedin
      url: "https://linkedin.com/in/francescortu"
    - name: instagram
      url: "https://instagram.com/francescortu"
    - name: mail
      url: "mailto:francescortu@live.it"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page



  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: bio
      name: Bio
      url: /bio/
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 30
    - identifier: Publications
      name: Publications
      url: /Publications/
      weight: 20
    - identifier: CV
      name: CV
      url: CV.pdf
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

copyright: "© 2023 Francesco Ortu -"